version: '3.8'
volumes:
  redis_data:
services:
  redis:
    container_name: nestjs-learning-redis
    image: redis:7.0-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - '36379:6379'
  app:
    depends_on:
      - redis
    image: node:18.16-alpine
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command: sh -c "yarn && yarn run start:dev"
    ports:
      - 30032:30032
networks:
  default:
    external:
      name: my-learning-net