version: '3.8'
services:
  app:
    image: node:18.16-alpine
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command: sh -c "yarn && yarn run start:dev"
    ports:
      - 30032:30032
networks:
  default:
    external:
      name: my-learning-net